In [23]:
from sklearn.datasets import make_regression
from sklearn.linear_model import SGDRegressor
import pandas as pd

In [4]:
data = make_regression(n_samples = 100,n_features = 3, random_state = 1 )
features = pd.DataFrame(data[0])
labels = pd.Series(data[1])

In [13]:
# In the language of graphs, a feedforward network is a directed, acyclic graph.
#  Gradient descent is the most common technique for fitting neural network models
#and we'll explore it in further detail in the third mission.

features['bias'] = 1

def train(features, labels):
    lr = SGDRegressor()
    lr.fit(features,labels)
    weights = lr.coef_
    return weights

def feedforward(features,weights):
    predictions = np.dot(features, weights.T)
    return predictions

In [21]:
train(features,labels)

array([4.41627368e+01, 9.89053756e+01, 5.81038700e+01, 9.30893505e-03])

In [26]:
from sklearn.linear_model import SGDClassifier
from sklearn.datasets import make_classification
import pandas as pd
import numpy as np

class_data = make_classification(n_samples=100, n_features=4, random_state=1)
class_features = pd.DataFrame(class_data[0])
class_labels = pd.Series(class_data[1])
class_features['bias'] = 1

def log_train(class_features, class_labels):
    sg = SGDClassifier()
    sg.fit(class_features, class_labels)
    return sg.coef_

def sigmoid(linear_combination):
    return 1/(1+np.exp(-linear_combination))

def log_feedforward(class_features, log_train_weights):
    linear_combination = np.dot(class_features,log_train_weights.T)
    log_predictions = sigmoid(linear_combination)
    log_predictions[log_predictions >= 0.5] = 1
    log_predictions[log_predictions < 0.5] = 0
    return log_predictions
    

# Uncomment this code when you're ready to test your functions.
log_train_weights = log_train(class_features, class_labels)
log_predictions = log_feedforward(class_features, log_train_weights)

In [27]:
print(log_train_weights)

[[ 18.94488862   3.69313012 -19.80725749  49.58868294   4.00160064]]


In [28]:
print(log_predictions)

[[0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]]
